import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  wikiSidebar: [
    { type: "autogenerated", dirName: "product-wiki" },
    // 外链到www.pisugar.com 
    { type: "link", label: "Official PiSugar Website", href: "https://www.pisugar.com" },

    // {
    //   type: "category",
    //   label: "PiSugar Battery / UPS",
    //   items: [
    //     {
    //       type: "link", // 添加外链
    //       label: "Official PiSugar Website",
    //       href: "https://www.pisugar.com",
    //     },
    //     {
    //       type: "category",
    //       label: "Docs", // 继续原来的目录结构
    //       items: [
    //         // 这里可以是现有的文档项或自定义链接
    //         "getting-started",
    //         "advanced-guides",
    //       ],
    //     },
    //   ],
    //   link: {
    //     type: "generated-index",
    //     description:
    //       "5 minutes to learn the most important Docusaurus concepts.",
    //   },
    // },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
