import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  wikiSidebar: [
    { type: "autogenerated", dirName: "product-wiki" },
  ],
  toolsSidebar: [
    { type: "autogenerated", dirName: "useful-tools" },
  ],
  faqSidebar: [
    {
      type: "category",
      label: "客户问题 FAQ",
      link: {
        type: "generated-index",
        title: "客户问题 FAQ",
        description: "PiSugar 常见客户问题及解决方案",
        slug: "/faq/customer-faq",
      },
      items: [{ type: "autogenerated", dirName: "faq" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
